site_name: Aplicação de Redes de Computadores
site_author: Andriéria Dantas

theme:
  language: pt
  name: material

repo_url: https://andrieria.github.io/apr-2023-2/
repo_name: andrieria/apr-2023-2
edit_uri: edit/main/docs

nav:
- index.md
- pedra.md
- papel.md
- tesoura.md

- Ensaios:
  - ensaios/mermaid.md


plugins:
- mermaid2
